// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkrtdkqbgtxvofdrzatc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcnRka3FiZ3R4dm9mZHJ6YXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTc1MzIsImV4cCI6MjA2NDk3MzUzMn0.TUML7JZndzJNDLk_vbbmuiawaXPlZRcf1odh-gnOqj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);